version: '3'

services:
  app:
    image: motd:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    #    environment:
    #      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge