name: MOTD CI/CD
run-name: ${{ github.actor }} is deploying MOTD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#env:
#  AWS_REGION: ap-northeast-2
#  AWS_S3_BUCKET: motd-bucket-v1
#  AWS_CODE_DEPLOY_APPLICATION: motd-cicd-CD
#  AWS_CODE_DEPLOY_GROUP: motd-cicd-CD-group

jobs:
  build-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - name: main 브랜치로 이동
        uses: actions/checkout@v3
        with:
          ref: main

      # 1. Java 17 세팅
      - name: JDK 21 설치
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      # 2. Spring Boot 애플리케이션 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean bootJar

      # 3. Docker 이미지 빌드
      - name: Docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/github-actions-demo .

      # 4. DockerHub 로그인
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 5. Docker Hub 이미지 푸시
      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/motd
