#env:
#  AWS_REGION: ap-northeast-2
#  AWS_S3_BUCKET: motd-bucket-v1
#  AWS_CODE_DEPLOY_APPLICATION: motd-cicd-CD
#  AWS_CODE_DEPLOY_GROUP: motd-cicd-CD-group

name: MOTD CI/CD
run-name: ${{ github.actor }} is deploying MOTD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: main 브랜치로 이동
        uses: actions/checkout@v4
        with:
          ref: main

      # Java 21 세팅
      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # gradle caching (빌드 시간 줄이기)
      - name: Gradle Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 환경별 yml 파일 생성
      - name: make application.yml
        if: contains(github.ref, 'main')
        run: |
          mkdir -p src/main/resources
          touch src/main/resources/application.yml
          touch src/main/resources/application-test.yml
          touch src/main/resources/application-prod.yml
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_TEST_YML }}" | base64 --decode > src/main/resources/application-test.yml
          echo "${{ secrets.APPLICATION_PROD_YML }}" | base64 --decode > src/main/resources/application-prod.yml
        shell: bash

      # gradle chmod
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Spring Boot 프로젝트 build
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Docker 이미지 빌드 & Push
      - name: Docker Image Build & Push
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/motd .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/motd


#  run-docker-image-on-ec2:
#    # build-docker-image 작업이 완료되어야 실행됨
#    needs: build-docker-image
#
#    # self-hosted-runner에서 동작
#    runs-on: self-hosted
#
#    steps:
#      # 1. 최신 이미지 Pull
#      - name: docker pull
#        run: |
#          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
#          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/project-name
#
#      # 2. 기존 컨테이너 중지
#      - name: docker stop container
#        run: docker stop $(docker ps -q) 2>/dev/null || true
#
#      # 3. 최신 이미지 컨테이너화하여 실행시
#      - name: docker run new container
#        run: docker run --rm -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/project-name
#
#      # 4. 기존 이미지 정리
#      - name: delete old docker image
#        run: docker system prune -f